### ISSUE TITLE
[Request]CTMLib as a standalone library.

### ISSUE THREAD

**Issue by raymondbh** [Chisel-Team/CTMLib#1]
Hi. I would love to use your lib in my TFC addon, but it seems that the lib actually depends on methods in the Chisel 2 mod... That's a little backwards for me.... Planing on making it a standalone library?

**Comment by tterrag1098** [comment]
It depends on the chisel API to compile, and that will be downloaded if you make this a maven dependency. It has no dependency on chisel at runtime.

**Comment by raymondbh** [comment]
Ok. I see, just used to that the mod depends on the library, not vise/versa... But anyhow, am I allowed to use some of your source in my mod? I need to do some modifications to it in order to get it to work...

**Comment by raymondbh** [comment]
In CTM.java there is a map to show how the ctm textures are glued together. Can I find the complete "map" for this? I can't get my texture to look nice...

**Comment by Drullkus** [comment]
You're going to need two image files. [One called '<file>.png'](https://github.com/Chisel-2/Chisel-2/blob/dev/src/main/resources/assets/chisel/textures/blocks/factory/iceiceice.png) and [other being '<file>-ctm.png'](https://github.com/Chisel-2/Chisel-2/blob/dev/src/main/resources/assets/chisel/textures/blocks/factory/iceiceice-ctm.png)

**Comment by Drullkus** [comment]
The first one is a single texture, what the texture will look like when there's no blocks next to it. 

X = Air
B = Your Block
O = Neighboring Block (Same block)

    X X X
    X B X
    X X X

The second file contains Four Textures side.

The top right texture is for vertical connections. Basically, what the texture will look like with only blocks on top and on bottom.

    X O X
    X B X
    X O X

The bottom left texture is for horizontal connections. It's what the texture will look like with blocks on its left and right.

    X X X
    O B O
    X X X

The bottom right texture is for connections on top, right, bottom, and left. It's what the texture will look like on the center block when your arrange the blocks in a + formation.

    X O X
    O B O
    X O X

The top left texture is for connections on all 8 spaces. It's what the texture looks in the center of a 3x3 block formation.

    O O O
    O B O
    O O O

If you need example textures, look at the two files mentioned in the previous post.

**Comment by Drullkus** [comment]
![2015-07-28_16 47 35](https://dl.dropboxusercontent.com/s/22jze3ftjo7567t/ExampleCTMLib.jpg)

**Comment by raymondbh** [comment]
Ok. thank you, I think I have it now :-)

**Comment by TheCricket** [comment]
Wow

**Comment by tterrag1098** [comment]
@Drullkus we should probably set up a wiki :p

**Comment by raymondbh** [comment]
That would be welcome.
I had to make this to wrap my head around it... :-)
https://goo.gl/photos/DKGubXopuSesnGob6

**Comment by Drullkus** [comment]
@raymondbh You did well. That was't so hard. No need to make 47 textures! (I looked up the actual count this time.) :)
