### ISSUE TITLE
Mod Wont Load

### ISSUE THREAD

**Issue by Gengi0927** [Chisel-Team/CTMLib#6]
This mod looks like it would be great, especially when combined with chiselsandbits, however, when i enter Minecraft, the game will not load the mod, for further information, i am using forge to run Minecraft 1.10.2, CTMLib is present, and there are no crash, lag or other issues with the mod, I would apprectiate it if someone would/could help, Thanks!

EDIT: By wont load i mean the mod will not show up in the game, when i enter the game it tells me i have 5 mods loaded, including Chisel, there would be 6, the chisels will not show up in NEI or JEI menus.

**Comment by tterrag1098** [comment]
This mod does not exist on 1.10, nor is it even a mod. It's just library code for other mods to use.

**Comment by Gengi0927** [comment]
I opened the wrong repository, sorry.
