### ISSUE TITLE
Invisible Ender IO Blocks

### ISSUE THREAD

**Issue by Rudy2D2** [Chisel-Team/CTMLib#7]
When this mod is installed, certain Ender IO blocks do not render. The travel anchor and conduit facades are affected, possibly other blocks. I have tested builds with just this mod and Ender IO + Ender Core and the problem persists, so it is definitely this mod.

**Comment by tterrag1098** [comment]
Wrong mod. >> https://github.com/Chisel-Team/ConnectedTexturesMod
